language: c

os: linux
dist: xenial
sudo: required

script:
    - sudo apt-get update && sudo apt-get install -y lsdiff gperf makeinfo lzop xsltproc
    - DISTRO=Lakka PROJECT=Chip ARCH=arm make image
