language: c

os: linux
dist: trusty
sudo: required

before_install:
    - docker pull elpinguino/lakkabuild

script:
    - docker run -v $PWD:/work -w /work elpinguino/lakkabuild "DISTRO=Lakka PROJECT=Chip ARCH=arm make image"
