language: c

os: linux
dist: trusty
sudo: required

before_install:
    - docker pull elpinguino/lakkabuild

script:
    - docker run -v $PWD:/work -w /work -e DISTRO=Lakka -e PROJECT=Chip -e ARCH=arm elpinguino/lakkabuild make image
